# Generated by Django 5.2.7 on 2025-11-03 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.IntegerField(default=5)),
                ('resource_limits', models.JSONField(default=dict)),
                ('weights', models.JSONField(default=dict)),
                ('recipes_off', models.JSONField(default=list)),
                ('inputs', models.JSONField(default=dict)),
                ('outputs', models.JSONField(default=dict)),
                ('max_item', models.CharField(blank=True, max_length=128, null=True)),
                ('checkbox_Nuclear_Waste', models.BooleanField(default=False)),
                ('integer_recipes', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
