# Generated by Django 5.2.7 on 2025-11-03 23:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0002_savedsettings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='savedsettings',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AddField(
            model_name='savedsettings',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='savedsettings',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='satopt_settings', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='savedsettings',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='savedsettings',
            name='settings',
            field=models.JSONField(),
        ),
        migrations.AlterUniqueTogether(
            name='savedsettings',
            unique_together={('owner', 'name')},
        ),
    ]
