# Generated by Django 5.2.7 on 2025-11-04 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0003_alter_savedsettings_options_savedsettings_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='defaultsettings',
            options={'verbose_name': 'Default settings', 'verbose_name_plural': 'Default settings'},
        ),
        migrations.AlterModelOptions(
            name='savedsettings',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Saved settings', 'verbose_name_plural': 'Saved settings'},
        ),
        migrations.AlterField(
            model_name='defaultsettings',
            name='inputs',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='defaultsettings',
            name='outputs',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='defaultsettings',
            name='recipes_off',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='defaultsettings',
            name='resource_limits',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='defaultsettings',
            name='weights',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
